steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '--build-arg', 'IMAGE=python:3.6.8', '-t', 'gcr.io/staff-232313/ssm-image', '-f', 'dockerX/ssm/Dockerfile', '.'
      ]
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/staff-232313/ssm-image']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/staff-ssm', 'nginx=gcr.io/staff-232313/ssm-image']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=staff-cluster'
      - 'ENV=stg'
      - 'DEBUG=True'
      - 'PROJECT=ssm'
      - 'PYTHONPATH=/usr/src/ssm/'
      - 'CORS_ORIGIN_ALLOW_ALL=True'
      - 'DJANGO_SETTINGS_MODULE=ssm.settings'
      - 'DATABASE_NAME=ssm_database'
      - 'TEST_DATABASE_NAME=test_ssm_database'
      - 'DATABASE_USER=${_DATABASE_USER}'
      - 'DATABASE_PASSWORD=${_DATABASE_PASSWORD}'
      - 'DATABASE_HOST=${_DATABASE_HOST}'
      - 'DATABASE_PORT=${_DATABASE_PORT}'
      - 'POSTGRES_USER=${_DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${_DATABASE_PASSWORD}'
      - 'POSTGRES_DB=ssm_database'
      - 'EMAIL_HOST_USER=test'
      - 'EMAIL_HOST_PASSWORD=test'
      - 'CELERY_BROKER_URL=redis://redis:6379/1'
      - 'CELERY_RESULT_BACKEND=redis://redis:6379/2'
      - 'SYSTEM_EMAIL=${_SYSTEM_EMAIL}'
      - 'SYSTEM_PASSWORD=${_SYSTEM_PASSWORD}'
timeout: 660s
tags: ['staff-build', 'staff-deploy']
